### ISSUE TITLE
API available to generate images ?

### ISSUE THREAD

**Issue by NathanMolinier** [ChristianToennes/VMRI#1]
Dear Sir/Madam,

I would like first to congratulate you for your work ! My name is Nathan, and I am a doctoral student at Polytechnique Montréal.

I have a query concerning the codebase and its capabilities. Specifically, I am interested in exploring the feasibility of generating brain images using an API, thus bypassing the necessity of utilizing the web interface.

I thank you for your time and any insights you may provide on this matter.

Sincerely,

Nathan

**Comment by ChristianToennes** [comment]
Hi,

since the images are calculated inside the browser there is no web service that generates the image and no api.
You could adapt my code to build a webserver with an api, but that would take a lot of work.
Maybe you can get source code from Daniel Treceño-Fernández who developed this mri software: https://www.mdpi.com/1424-8220/21/18/6011 It has a web service with an API.
